### ISSUE TITLE
Include fix for ResInsight in main opm-flowdiagnostics repository

### ISSUE THREAD

**Issue by magnesj** [OPM/opm-flowdiagnostics-applications#96]
I think the following issue is not merged into master
https://github.com/OPM/ResInsight/pull/4491

Should it?

**Comment by bska** [comment]
> I think the following issue (OPM/ResInsight#4491) is not merged into master

It should be and I'll do so.  We're in a little bit of a tight spot at the moment because the upstream "opm-common" module no longer brings in libecl, but we'll add the necessary bits to our build system.
