### ISSUE TITLE
Improve robustness for PVT data extraction

### ISSUE THREAD

**Issue by magnesj** [OPM/opm-flowdiagnostics-applications#97]
Some datasets are missing PVT data. Guard further processing if this situation occurs.

**Comment by bska** [comment]
Just out of curiosity, do you know which software package produces an ECLIPSE-compatible result set withouth outputting PVT tables to the `TAB` vector in the `.INIT` file?  I **suppose** E300 might do this&mdash;its tables are sufficiently different from those of E100 that the entries might be stored elsewhere&mdash;but both E100 and OPM Flow should always output compatible PVT tables (at least if OPM/opm-common#694 does not hit).

**Comment by magnesj** [comment]
@hhgs says that the test dataset we have been using has been run using E300 (Equinor internal case name is TEST10K_FLT_LGR_NNC.EGRID )

**Comment by hhgs** [comment]
INIT-file keyword INTEHEAD item 95 IPROG = simulation program identifier:
100 = ECLIPSE 100, 300 = ECLIPSE 300,  500 = ECLIPSE 300 (thermal), 700 = INTERSECT, 800 = FrontSim, negative = Other simulator
